### ISSUE TITLE
How to read time fields?

### ISSUE THREAD

**Issue by ophiry** [tcalmant/python-javaobj#15]
i'm having troubles reading time objects - the resulting object contains an 8 byte binary buffer, but I'm not sure how to interpret it

example: (serialized date is around 1/1/2016)

    serialized_time_object = '\xac\xed\x00\x05sr\x00\rjava.time.Ser\x95]\x84\xba\x1b"H\xb2\x0c\x00\x00xpw\x08\x05\x00\x00\x07\xe0\x01\x01\xffx'
    
    time_object = javaobj.loads(serialized_time_object)
    
    time_object.__dict__

> {'annotations': ['\x05\x00\x00\x07\xe0\x01\x01\xff'],  'classdesc':
> [java.time.Ser:0x-6AA27B45E4DDB74E]}

    struct.unpack('L',time_object.annotations[0])(0)

> 18374970016350076933L

**Comment by tcalmant** [comment]
Hi,
Java uses a custom serialization for this type of object, [as can be seen in the source](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/time/Ser.java#244).

It is therefor necessary to read the content of ``annotations`` as the bytes written by the JVM, therefore you have to read:
1. A byte indicating the type
2. The time, according to the type

In the case of your snippet, we get "type" as 5: ``LocalDateTime``, which is in fact serialized as a ``LocalDate`` followed by a ``LocalTime``.

This following snippet handles this kind of times, following the source code of ``java.time.Ser``, ``LocalDate`` and ``LocalTime``.
Note that '>' in format string is mandatory as Java serialization uses Big Endian.

```python
import javaobj
import struct

serialized_time_object = b'\xac\xed\x00\x05sr\x00\rjava.time.Ser\x95]\x84\xba\x1b"H\xb2\x0c\x00\x00xpw\x08\x05\x00\x00\x07\xe0\x01\x01\xffx'
time_object = javaobj.loads(serialized_time_object)

def read(data, fmt_str):
    size = struct.calcsize(fmt_str)
    return struct.unpack(fmt_str, data[:size]), data[size:]

# This is for Python 3, to ensure we have bytes
data = time_object.annotations[0].encode('latin1')

# This will give us the kind of date (type 5: [LocalDateTime](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/time/Ser.java#100))
(time_type,), data = read(data, '>b')

Now we just have to follow the deserialization process from the Java source code:
# Start with the date
(year, month, day_of_month), data = read(data, '>ibb')

# Then the time
(hour,), data = read(data, '>b')
minute = 0
second = 0
nano = 0

if hour < 0:
    hour = ~hour
else:
    minute = read(data, '>b')
    if minute < 0:
        minute = ~minute
    else:
        second = read(data, '>b')
        if second < 0:
            second = ~second
        else:
            nano = read(data, '>i')

print("Date:", year, month, day_of_month, hour, minute, second, nano)
```
