### ISSUE TITLE
DefaultObjectTransformer to support HashSet

### ISSUE THREAD

**Issue by jwon** [tcalmant/python-javaobj#25]
`DefaultObjectTransformer` supports `ArrayList`, `LinkedList`, `HashMap`, `LinkedHashMap`, and `TreeMap` today.

It would be great if we could support the `Set` classes from `java.util` as well (e.g. `HashSet` or `TreeSet`, etc.)

It should correspond to a Python `set` object.

Thank you!

**Comment by tcalmant** [comment]
That seems to be feasible, at least for `HashSet`.
This could be done for next week.

**Comment by jwon** [comment]
Thank you so much! 👍

**Comment by tcalmant** [comment]
I still can't figure out why `LinkedHashSet` doesn't work... I think I'll stay with `HashSet` support for now (o allow a release of 0.3.0), with a note in the README.
