### ISSUE TITLE
sync with original project

### ISSUE THREAD

**Issue by matthieucan** [tcalmant/python-javaobj#3]
link: https://github.com/vbuell/python-javaobj/commits/master

Cheers!

**Comment by tcalmant** [comment]
Done in latest release (0.1.3)

**Comment by matthieucan** [comment]
Well done Thomas :)

**Comment by pombredanne** [comment]
@tcalmant have you thought about merging with @vbuell to maintain a py2/3 codebase together?

**Comment by tcalmant** [comment]
I haven't contacted @vbuell for a while but that could be a benefit for the project maintenance.
