### ISSUE TITLE
Include License in pypi distribution

### ISSUE THREAD

**Issue by CJ-Wright** [tcalmant/python-javaobj#36]
Would it be possible to include the license in the pypi distribution via a [`manifest.in`](https://github.com/pypa/sampleproject/blob/master/MANIFEST.in) file? This would help a lot with downstream packaging like conda-forge.
https://github.com/conda-forge/javaobj-py3-feedstock/pull/2

**Comment by tcalmant** [comment]
Hi,
I won't be able to change the project before Thursday, but I can do that for a 0.4.0.1 version.
Also, two questions:
* does the file require the `.txt` extension or do I keep it as is ?
* do I need to add an entry in setup.cfg/setup.py to link to the license file ?

**Comment by CJ-Wright** [comment]
Thank you very much!

I don't think it needs to have an extension, and I don't think you need to link to it in the setup.py.

**Comment by tcalmant** [comment]
Hi Christopher,
I've published v0.4.0.1 that includes the LICENSE, the README and the AUTHORS.
I've also added an entry in setup.py to force the license file name to LICENSE.

Also, the requirements were missing in setup.py.

I let you close the issue if everything works on your side.

**Comment by CJ-Wright** [comment]
Thank you very much! The current build checks out! https://github.com/conda-forge/javaobj-py3-feedstock/pull/3
