### ISSUE TITLE
Import numpy only when it is really used

### ISSUE THREAD

**Issue by sarimak** [tcalmant/python-javaobj#44]
We need to **set NumPy/OpenBLAS thread limit via environment variable before NumPy is imported**.

Value of the thread limit is stored in our central configuration service to which we connect over network, using TLS configured via Java truststore and certstore. So we have to first import `jks` which imports `javaobj` (API v1) which imports `numpy` -- so we are able to get the thread limits but NumPy ignores them because javaobj imported it too early.

Would it be possible to move the import of `numpy` from module-level into `class JavaObjectUnmarshaller`'s constructor and do the import only when `use_numpy_arrays` is `True`? The `jks` uses default value of `use_numpy_arrays` (False) so we would avoid importing `numpy`.

**Comment by tcalmant** [comment]
Fixed by #45 and released with version 0.4.2
