### ISSUE TITLE
StringIO for Python3

### ISSUE THREAD

**Issue by jeswils-ap** [tcalmant/python-javaobj#49]
This package is using StringIO from the StringIO package, which throws an error for Python3.

**Comment by tcalmant** [comment]
Hi,
Could you be more precise on the error ?
The package is made to work on both Python 2 and 3, hence the import of `StringIO.StringIO` (Python 2) and the fallback on `io.BytesIO` (Python 3) via the handling of an `ImportError`.

**Comment by jeswils-ap** [comment]
Sorry, you're right. Bad requirements doc pulled the incorrect javaobj package.
