### ISSUE TITLE
Marshalling a JavaByteArray

### ISSUE THREAD

**Issue by ElDavoo** [tcalmant/python-javaobj#52]
Hello,
how can I serialize a JavaByteArray?
I get:
`AttributeError: 'NoneType' object has no attribute 'name'`

**Comment by ElDavoo** [comment]
Followup:
The are two problems:
1) When I build a JavaByteArray object, the class description is not filled in by default. This makes the program crash later when I call the dumps function on it. Is it even legal to have an object without its class description?    
I solved this problem by manually building the class description and passing it to the JavaByteArray constructor. In this way I have a JavaByteArray with its class description filled in correctly.

How it is right now:
```
cdesc = javaobj.JavaClass()
cdesc.flags = 2
cdesc.name = '[B'
cdesc.serialVersionUID = -5984413125824719648
barr = javaobj.JavaByteArray(b'\x00'*32, cdesc)
```  
How I would like it to be:  
`barr = javaobj.JavaByteArray(b'\x00'*32)  
`

------------------

2) The writeObject method is marshaller.py does not recognize JavaByteArray but only JavaArray. This makes the method to mistakenly call write_object, which won't work properly. The end result is a stream composed only by the header, without data following.  
The solution is as simple as:
```
        if isinstance(obj, JavaArray):
            # Deserialized Java array
            self.write_array(obj)
+      elif isinstance(obj, JavaByteArray):
+          # Deserialized Java bytearray
+          self.write_array(obj)
```
And it will make marshalling of JavaByteArray possible.

**Comment by tcalmant** [comment]
Hi,

1. As the JavaByteArray is supposedly a well know class, we could consider a default classdesc if None is given as argument [at its creation](https://github.com/tcalmant/python-javaobj/blob/master/javaobj/v1/beans.py#L213).

2. The JavaByteArray is indeed missing from the marshaller, it should be added as you did.
Another solution could be to make JavaByteArray inherit JavaArray, but that will likely lead to other issues.

Could you create a pull request with those changes?

**Comment by ElDavoo** [comment]
> 1. As the JavaByteArray is supposedly a well know class, we could consider a default classdesc if None is given as argument at its creation.

That would create an inconsistent behaviour if we were to create a default classdesc only to JavaByteArrays, if it is done it should be done for all supported objects
