### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ElDavoo** [tcalmant/python-javaobj#55]
Hello,
as PyPi does not allow direct dependencies, I can't release a new pip package that depends on this repo's current branch.  
would it be possible to release a 0.4.4 please? 
Thank you!

**Comment by tcalmant** [comment]
Hi @ElDavoo 
I've released version 0.4.4.
Sorry for not having done it earlier

**Comment by ElDavoo** [comment]
No worries! I would rather blame it to pypi for not allowing direct dependencies.
